### ISSUE TITLE
[Documentation] Fix README example of a model

### ISSUE THREAD

**Issue by pixelhandler** [ember-data/ember-data-live-filter-by#3]
This is confusing:

```
// app/models/post.js

export default Ember.Controller.extend({

  comments: DS.hasMany('comment'),

  maintainedComments: Ember.computed('comments.@each.isDeleted', function() {
    return this.get('comments').filterBy('isDeleted', false);
  })
});
```

It appears that a model example should not use `Ember.Controller.extend` in the code example.

See https://github.com/ember-data/ember-data-live-filter-by/blob/master/README.md#i-dont-want-to-use-this-addon-are-there-alternatives

**Comment by bmac** [comment]
Thanks for pointing this out @pixelhandler. I have updated the example to use `DS.Model` instead of `Ember.Controller` https://github.com/ember-data/ember-data-live-filter-by/commit/4ee18b0ba37ea14d7ecf576e0cd60da20e2b4b3f. I'm going to close this issue for now but please let me know if it is still confusing.
